config/routes.rb
Rails.application.routes.draw do   
 
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
   resources :posts do
    resources :comments
  end

   get 'blogs'    => 'blogs#index'
    devise_for :users
    root 'static_pages#home'
    get 'users/new'
    get 'help'    => 'static_pages#help'
    get 'about'   => 'static_pages#about'
    get 'contact' => 'static_pages#contact'
    post 'static_pages/create'
    post 'connects'    => 'static_pages#connect'
    get 'product' => 'static_pages#product'

end

app/models/Pet.rb
class Pet
	include Mongoid::Document
	field :name, type: String
	
end

app/models/Pettype.rb
class Pettype
	include Mongoid::Document
	field :pet_name, type: String
	
end

app/models/category.rb
class Category
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
  field :created_at, type: Time, default: DateTime.now
  field :modified_at,    type: Time
   mount_uploader :image, ImageUploader
  has_many :posts
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  # field :name, type: String
  field :user_id, type: String
  field :content, type: String
  field :created_at, type: Time, default: DateTime.now
  embedded_in :post, :inverse_of => :comments
end

app/models/connect.rb
class Connect
  include Mongoid::Document
  field :firstname, type: String 
  field :lastname, type: String
  field :email, type: String
  field :petnames, type: String
  field :pet_id, type: String
  field :created_at, type: Time, default: DateTime.now
  belongs_to :pet  #relatioship with another table
  validates_presence_of :firstname
  validates_presence_of :email
end

app/models/contact.rb
class Contact
  include Mongoid::Document
  field :email, type: String
  field :firstname, type: String
  field :lastname, type: String
  field :petnames, type: String   
  field :inquiry_id, type: String
  field :help_reason, type: String
  field :created_at, type: Time, default: DateTime.now
  belongs_to :inquiry
  validates_presence_of :firstname, :email, :help_reason
end

app/models/inquiry.rb
class Inquiry
	include Mongoid::Document
	field :inquiry_name, type: String
	
end

app/models/pet.rb
class Pet
	include Mongoid::Document
	field :pet_name, type: String
	
end

app/models/post.rb
class Post
  include Mongoid::Document
  field :category_id, type: String
  field :name, type: String
  field :content, type: String
  field :created_at, type: Time, default: DateTime.now
  field :modified_at,    type: Time
  mount_uploader :image, ImageUploader
  validates_presence_of :name
  embeds_many :comments
  accepts_nested_attributes_for :comments
  belongs_to :category
  rails_admin do
  	list do
      include_all_fields
      exclude_fields :_id
    end
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""
  field :first_name,          type: String, default: ""
  
  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String
  field  :admin ,type:Boolean

  ## Confirmable
   field :confirmation_token,   type: String
   field :confirmed_at,         type: Time
   field :confirmation_sent_at, type: Time
   field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
  
  field :email, type: String
  field :created_at, type: Time, default: DateTime.now
  field :modified_at,    type: Time, default: DateTime.now
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
     @posts = if params[:search]
               Post.where(name: params[:search])
             else
               Post.all
             end
    @categories=Category.all()
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :content).merge( :modified_at => DateTime.now)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "Petception"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end


 def comment
end

end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/devise---/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/layouts/_footer.html.erb
<section class="get_social">
<div class="row">
  <div class="large-12 columns text-center">
    <h2>Get social with Petception Now!</h2>
    <div class="social_wrap">
     <a class="facebook" href="https://www.facebook.com/Petception">facebook</a>
     <a class="twitter" href="https://twitter.com/PetCeption">twitter</a>
     <a class="google" href="https://plus.google.com/+PetCeption/posts/p/pub">google</a>
     <a class="youtube"  href="https://www.youtube.com/user/PetCeption/featured?view_as=public">youtube</a>    
<%= image_tag("social-down3.png", :alt => "") %>
  </div>
  </div>
</div> 
<div class="copyright">
  <div class="row">
    <div class="large-12 columns text-center">
     <p>Copywrite 2015 PetCeption| All Rights Reserved</p>
    </div>
  </div>
</div>
</section>
<script type="text/javascript">
  $.noConflict();
 jQuery(document).ready(function(){
          jQuery(".left-off-canvas-toggle").click(function(){
             jQuery(".top-bar").toggleClass("open");
          });
      });

  jQuery(function() {
    jQuery('a[href*=#]:not([href=#])').click(function() {
      if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
        var target = jQuery(this.hash);
        target = target.length ? target : jQuery('[name=' + this.hash.slice(1) +']');
        if (target.length) {
          jQuery('html,body').animate({
            scrollTop: target.offset().top
          }, 1200);
          return false;
        }
      }
    });
  });

</script>
  

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<div  class="row">
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>
</div>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>

 <div class="logo left tests">
 <%=link_to image_tag("logo.png", alt: "Rails logo"),root_path %>     
   </div>

 <div class="header_middle left text-right">
        <div class="headtext">Be first to have your own one-of-a-kind petcam!</div>
         <section class="top-bar right">
            <ul class="off-canvas-list sub-nav">
            <%= render 'layouts/navigation_links' %>                          
            </ul>
          </section>
        <nav class="tab-bar mobile-menu">
            <section class="left-small">
              <a class="left-off-canvas-toggle menu-icon" aria-expanded="false"><span></span></a>
            </section>
          </nav> 
        </div>
         <div class="header-right right text-right">
            <a class="custom-button radius button" href="#connectWith">Submit Info Now<small>to Connect with us</small></a>
        </div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
 <li><%= link_to 'Home', root_path %></li>
<li><%= link_to 'Contact-Us',  contact_path %></li>
<li><%= link_to 'product',  product_path %></li>
<li><%= link_to 'Blog',  posts_path %></li>
<% #comment do %>
<% if user_signed_in? %>
 <li>   Welcome <%=  current_user.first_name %>
    <%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
<% else %>
<li>    <%= link_to "Sign in", new_user_session_path%>  </li> 

   <li> <%= link_to "Sign up", new_user_registration_path %></li>
<% end %>

<%# end %>

app/views/layouts/admin--/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/admin--/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>


<nav class="top-bar" data-topbar  role="navigation">
  <ul class="title-area ">
    <li class="name"><h1> <%= link_to "Petception", '#', id: "logo" %></h1></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul class="right">
      <%= render 'layouts/admin/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/admin--/_navigation_links.html.erb
<%# add navigation links to this file %>
 <li><a href="#">home</a></li>
<li><a href="#">Contact-Us</a></li>
<li><a href="#">Product</a></li>
<li><a href="#">Blog</a></li> 

app/views/layouts/admin--/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Peteception" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/admin/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/admin/messages' %>
       <%= yield %>
    </main>
    <footer >
  <section class="small-4 columns">
    Copyright 2013
  </section>
  <section class="small-4 columns">
    All rights reserved.
  </section>
</footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= full_title(yield(:title)) %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Peteception" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  <div data-magellan-expedition="fixed">
  <div class="header-nav">
   <div class="row">
    <div class="small-12 columns">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    </div>
    </div>
    </div>
  </div>
<!-- closing of header -->
 <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
     </main>
<!-- starting of get social section --> 
<%= render 'layouts/footer' %>

  </body>
</html>